### PR TITLE
created tour page

### PR DESCRIPTION
**Pull request by ghost**
# How to Test
- checkout to ad-7-tourPage
- click on the tour link to go to the tour page
- click go back home to go back to index

(going to remove links after testing)

### CODE REVIEW

**Comment by AlexOrga** [comment]
fist with a skywardly protruding digit....which digit do you think it is?

**Comment by ghost** [comment]
@AlexOrga Is it a thumb???

**Comment by Cgatewood55** [comment]
:+1: :100:

**Comment by ghost** [comment]
lookin goood

**Comment by ledugani** [comment]
🥇

**Pull request merged**
