### PR TITLE
Ad 51 style footer

### PR DESCRIPTION
**Pull request by ghost**
Should see on all pages
screen shot 2018-03-18 at 11 43 03 pm

### CODE REVIEW

**Comment by ghost** [comment]
👍

**Comment by ledugani** [comment]
👍

**Comment by AlexOrga** [comment]
👍

**Comment by ledugani** [comment]
Looks good now 👍

**Comment by Cgatewood55** [comment]
:+1:

**Comment by AlexOrga** [comment]
👍

**Pull request merged**
