### PR TITLE
styles + photo pg created

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by AlexOrga** [comment]
Are the images supposed to be displayed using javascript?

**Comment by ghost** [comment]
@AlexOrga i removed the hardcoded html and will be doing the JS to print photos using another card

**Comment by AlexOrga** [comment]
👍

**Comment by ghost** [comment]
👍

**Comment by ledugani** [comment]
lookin good 👍

**Comment by Cgatewood55** [comment]
:+1:

**Pull request merged**
