### PR TITLE
created band member page with boilerplate html

### PR DESCRIPTION
**Pull request by AlexOrga**
How to test

Created links to for you to navigate to and from the band members page.  I will delete links before I merge but after getting approval to merge.

### CODE REVIEW

**Comment by ghost** [comment]
links are working, looks awesome 👍

**Comment by ledugani** [comment]
looks good chief 👍

**Comment by ghost** [comment]
I can see the img director now 👍

**Comment by Cgatewood55** [comment]
:+1:

**Comment by ghost** [comment]
looks grate

**Pull request merged**
